# Embed a web resource file into a generated C++ header as a string literal.
#
# Invoked with `cmake -P` from a custom command so the header is regenerated
# whenever the source file changes:
#   cmake -DINPUT=<file> -DOUTPUT=<header> -DSYMBOL=<fn name> -P EmbedWebResource.cmake
#
# The generated header exposes:  std::string myplugin::<SYMBOL>()
# returning the file's contents. The contents are written as a raw string
# literal with a distinctive delimiter, so HTML/CSS/JS (quotes, backslashes,
# ${...}) pass through verbatim without escaping.

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
  message(FATAL_ERROR "EmbedWebResource.cmake requires -DINPUT, -DOUTPUT and -DSYMBOL")
endif()

file(READ "${INPUT}" CONTENT)

# Guard against the (very unlikely) case of the delimiter appearing in the file.
if(CONTENT MATCHES "\\)MPLUG_RES\"")
  message(FATAL_ERROR "EmbedWebResource: ${INPUT} contains the raw-string delimiter")
endif()

file(WRITE "${OUTPUT}"
"// Generated by cmake/EmbedWebResource.cmake — do not edit.
// Source: ${INPUT}
#pragma once

#include <string>

namespace myplugin
{

inline std::string ${SYMBOL}()
{
  return std::string(R\"MPLUG_RES(${CONTENT})MPLUG_RES\");
}

}  // namespace myplugin
")
